name: 'RewardADs'
version: '6.1'
main: it.nathanub.rewardads.SpigotMain
api-version: '1.14'
description: 'RewardADs official library for Spigot'
author: "Nathanub, WiinUp_YT"
commands:
  rewardads:
    description: 'Spam command and for reload'
  confirm:
    description: 'Verify your server'